// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MPApiService.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PostModel
    {
        /// <summary>
        /// Initializes a new instance of the PostModel class.
        /// </summary>
        public PostModel() { }

        /// <summary>
        /// Initializes a new instance of the PostModel class.
        /// </summary>
        public PostModel(string domainId = default(string), string appId = default(string), string signature = default(string), string msgSignature = default(string), string timestamp = default(string), string nonce = default(string), string token = default(string), string encodingAESKey = default(string))
        {
            DomainId = domainId;
            AppId = appId;
            Signature = signature;
            MsgSignature = msgSignature;
            Timestamp = timestamp;
            Nonce = nonce;
            Token = token;
            EncodingAESKey = encodingAESKey;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "domainId")]
        public string DomainId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appId")]
        public string AppId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "signature")]
        public string Signature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "msg_Signature")]
        public string MsgSignature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public string Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nonce")]
        public string Nonce { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "encodingAESKey")]
        public string EncodingAESKey { get; set; }

    }
}
