ALTER TABLE `le_orders_lines`
ADD COLUMN	`PriceFull` DECIMAL(9,2) NOT NULL DEFAULT '0.00' COMMENT '满减（满）',
ADD COLUMN	`CountFull` DECIMAL(9,2) NOT NULL DEFAULT '0.00' COMMENT '满减（满）（数量）',
ADD COLUMN	`CountReduction` DECIMAL(9,2) NOT NULL DEFAULT '0.00' COMMENT '满减（满）（数量）',
ADD COLUMN	`PriceReduction` DECIMAL(9,2) NOT NULL DEFAULT '0.00' COMMENT '满减（减）',
ADD COLUMN	`TermOfValidity` VARCHAR(50) NULL DEFAULT '0' COMMENT '有效期',
ADD COLUMN	`Discount` DECIMAL(9,2) NOT NULL DEFAULT '0.00' COMMENT '折扣',

ADD COLUMN	`Integral` INT(11) NOT NULL DEFAULT '0' COMMENT '积分'

