//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_admin
    {
        public int AdminID { get; set; }
        public string loginname { get; set; }
        public string nickname { get; set; }
        public string telephone { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string email { get; set; }
        public int status { get; set; }
        public int Roleid { get; set; }
        public string Address { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime Createtime { get; set; }
    }
}
