//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_admin_role_value
    {
        public int ID { get; set; }
        public int AdminRoleID { get; set; }
        public int NavigationID { get; set; }
        public int ActionType { get; set; }
    
        public virtual le_navigation le_navigation { get; set; }
    }
}
