//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public le_admin()
        {
            this.le_admin_re_users = new HashSet<le_admin_re_users>();
            this.le_orders_head = new HashSet<le_orders_head>();
            this.le_orders_head_log = new HashSet<le_orders_head_log>();
            this.le_orders_lines = new HashSet<le_orders_lines>();
            this.le_orders_lines_log = new HashSet<le_orders_lines_log>();
            this.le_orders_timelimit = new HashSet<le_orders_timelimit>();
            this.lel_admin_suppliers = new HashSet<lel_admin_suppliers>();
            this.le_goods_log = new HashSet<le_goods_log>();
        }
    
        public int AdminID { get; set; }
        public string LoginName { get; set; }
        public string Nickname { get; set; }
        public string TelePhone { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Email { get; set; }
        public int Status { get; set; }
        public int Roleid { get; set; }
        public string AdminRoleStr { get; set; }
        public string Address { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime Createtime { get; set; }
        public int IsUrgent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_admin_re_users> le_admin_re_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_head> le_orders_head { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_head_log> le_orders_head_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_lines> le_orders_lines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_lines_log> le_orders_lines_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_timelimit> le_orders_timelimit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lel_admin_suppliers> lel_admin_suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_goods_log> le_goods_log { get; set; }
    }
}
