//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_goods_value
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public le_goods_value()
        {
            this.le_cart_goodsvalue = new HashSet<le_cart_goodsvalue>();
            this.le_orderline_goodsvalue = new HashSet<le_orderline_goodsvalue>();
        }
    
        public int GoodsValueID { get; set; }
        public string GoodsValue { get; set; }
        public int Enable { get; set; }
        public string SerialNumber { get; set; }
        public int CategoryType { get; set; }
        public int GoodsID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<int> Stock { get; set; }
        public int RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_cart_goodsvalue> le_cart_goodsvalue { get; set; }
        public virtual le_goods le_goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orderline_goodsvalue> le_orderline_goodsvalue { get; set; }
    }
}
