//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_goods_log
    {
        public int OperationRecordID { get; set; }
        public int AdminID { get; set; }
        public int GoodsID { get; set; }
        public string BeforeGoodsName { get; set; }
        public string AfterGoodsName { get; set; }
        public decimal BeforeSpecialOffer { get; set; }
        public Nullable<decimal> AfterSpecialOffer { get; set; }
        public int BeforeSheLvesStatus { get; set; }
        public Nullable<int> BeforeMinimumPurchase { get; set; }
        public Nullable<int> AfterMinimumPurchase { get; set; }
        public Nullable<int> AfterSheLvesStatus { get; set; }
        public int BeforeStock { get; set; }
        public Nullable<int> AfterStock { get; set; }
        public int BeforeQuota { get; set; }
        public Nullable<int> AfterQuota { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual le_admin le_admin { get; set; }
        public virtual le_goods le_goods { get; set; }
    }
}
