//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_orders_head
    {
        public int Orders_Head_ID { get; set; }
        public string Out_Trade_No { get; set; }
        public string RcAddr { get; set; }
        public string RcName { get; set; }
        public string RcPhone { get; set; }
        public decimal Money { get; set; }
        public int Status { get; set; }
        public string Head_Notes { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> AdminID { get; set; }
        public int UsersID { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public int LinesCount { get; set; }
    
        public virtual le_users le_users { get; set; }
    }
}
