//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_orders_lines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public le_orders_lines()
        {
            this.le_orderline_goodsvalue = new HashSet<le_orderline_goodsvalue>();
            this.le_orders_lines_log = new HashSet<le_orders_lines_log>();
        }
    
        public int OrdersLinesID { get; set; }
        public int OrderHeadID { get; set; }
        public int GoodsID { get; set; }
        public decimal GoodsPrice { get; set; }
        public decimal SupplyPrice { get; set; }
        public int GoodsCount { get; set; }
        public int DeliverCount { get; set; }
        public decimal Profit { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
        public Nullable<int> AdminID { get; set; }
        public int UsersID { get; set; }
        public int SuppliersID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public decimal PriceFull { get; set; }
        public decimal CountFull { get; set; }
        public decimal CountReduction { get; set; }
        public decimal PriceReduction { get; set; }
        public decimal Discount { get; set; }
        public int Integral { get; set; }
    
        public virtual le_admin le_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orderline_goodsvalue> le_orderline_goodsvalue { get; set; }
        public virtual le_orders_head le_orders_head { get; set; }
        public virtual le_suppliers le_suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_lines_log> le_orders_lines_log { get; set; }
        public virtual le_goods le_goods { get; set; }
        public virtual le_users le_users { get; set; }
    }
}
