//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_orders_lines_mapping
    {
        public int ID { get; set; }
        public string OutTradeNo { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string Remarks { get; set; }
        public string Types { get; set; }
        public int PrintingTimes { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
