//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_orders_head_log
    {
        public int HeadRecordID { get; set; }
        public int OrderHeadID { get; set; }
        public int BeforeCount { get; set; }
        public Nullable<int> AfterCount { get; set; }
        public decimal BeforeAmount { get; set; }
        public Nullable<decimal> AfterAmount { get; set; }
        public int BeforeStatus { get; set; }
        public Nullable<int> AfterStatus { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<decimal> BeforeSupplierAmout { get; set; }
        public Nullable<decimal> AfterSupplierAmout { get; set; }
        public string Actions { get; set; }
        public Nullable<System.DateTime> BeforePickUpTime { get; set; }
        public Nullable<System.DateTime> AfterPickUpTime { get; set; }
    
        public virtual le_admin le_admin { get; set; }
        public virtual le_orders_head le_orders_head { get; set; }
        public virtual le_suppliers le_suppliers { get; set; }
        public virtual le_users le_users { get; set; }
    }
}
