//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_orders_lines_log
    {
        public int LinesRecordID { get; set; }
        public int OrderLineID { get; set; }
        public int BeforeCount { get; set; }
        public Nullable<int> AfterCount { get; set; }
        public decimal BeforeMoney { get; set; }
        public Nullable<decimal> AfterMoney { get; set; }
        public int BeforeStatus { get; set; }
        public Nullable<int> AfterStatus { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual le_admin le_admin { get; set; }
        public virtual le_suppliers le_suppliers { get; set; }
        public virtual le_users le_users { get; set; }
        public virtual le_orders_lines le_orders_lines { get; set; }
    }
}
