//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_orders_timelimit
    {
        public int ID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int AdminID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int TimeSlot { get; set; }
        public int LimitOrderCount { get; set; }
        public int CurrentOrderCount { get; set; }
    
        public virtual le_admin le_admin { get; set; }
    }
}
