//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_orders_lines
    {
        public int Orders_Lines_ID { get; set; }
        public string Out_Trade_No { get; set; }
        public int Goods_ID { get; set; }
        public decimal Money { get; set; }
        public int GoodsCount { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
        public Nullable<int> AdminID { get; set; }
        public int UsersID { get; set; }
        public Nullable<int> SuppliersID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> Category1 { get; set; }
        public Nullable<int> Category2 { get; set; }
        public Nullable<int> Category3 { get; set; }
        public Nullable<int> Category4 { get; set; }
        public Nullable<int> Category5 { get; set; }
    
        public virtual le_goods le_goods { get; set; }
        public virtual le_goods_value le_goods_value { get; set; }
        public virtual le_goods_value le_goods_value1 { get; set; }
        public virtual le_goods_value le_goods_value2 { get; set; }
        public virtual le_goods_value le_goods_value3 { get; set; }
        public virtual le_goods_value le_goods_value4 { get; set; }
        public virtual le_suppliers le_suppliers { get; set; }
    }
}
