//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_pushmsg
    {
        public int ID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int MsgCount { get; set; }
        public string OrderNo { get; set; }
        public int UserType { get; set; }
        public int UserID { get; set; }
        public int IsDeleted { get; set; }
        public int MsgType { get; set; }
    }
}
