//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public le_suppliers()
        {
            this.le_goods_suppliers = new HashSet<le_goods_suppliers>();
            this.le_order_pack = new HashSet<le_order_pack>();
            this.le_orders_head_log = new HashSet<le_orders_head_log>();
            this.le_orders_lines_log = new HashSet<le_orders_lines_log>();
            this.lel_admin_suppliers = new HashSet<lel_admin_suppliers>();
            this.le_orders_lines = new HashSet<le_orders_lines>();
        }
    
        public int SuppliersID { get; set; }
        public string SuppliersName { get; set; }
        public string ResponPeople { get; set; }
        public string MobilePhone { get; set; }
        public string PassWord { get; set; }
        public string Salt { get; set; }
        public string Email { get; set; }
        public string HeadImage { get; set; }
        public string IDImgA { get; set; }
        public string IDImgB { get; set; }
        public string BusinessImg { get; set; }
        public string AttachImg1 { get; set; }
        public string AttachImg2 { get; set; }
        public string Addr { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string IDCardNo { get; set; }
        public string BusinessNo { get; set; }
        public string FinanceName { get; set; }
        public string FinancePhone { get; set; }
        public string AuthCode { get; set; }
        public string Remarks { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string IMEI { get; set; }
        public string Initial { get; set; }
        public string Landline { get; set; }
        public string Deliverer { get; set; }
        public string DelivererPhone { get; set; }
        public string CustomerService { get; set; }
        public string CustomerServicePhone { get; set; }
        public string Docker { get; set; }
        public string DockerPhone { get; set; }
        public string Zoning { get; set; }
        public string CartModel { get; set; }
        public string Classify { get; set; }
        public string Category { get; set; }
        public string ManagingBrands { get; set; }
        public string AnotherName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_goods_suppliers> le_goods_suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_order_pack> le_order_pack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_head_log> le_orders_head_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_lines_log> le_orders_lines_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lel_admin_suppliers> lel_admin_suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_lines> le_orders_lines { get; set; }
    }
}
