//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_sys_address
    {
        public int AddressID { get; set; }
        public string ReceiveName { get; set; }
        public string ReceivePhone { get; set; }
        public string ReceiveArea { get; set; }
        public string ReceiveAddress { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Status { get; set; }
        public int Sort { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Img { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string Remarks { get; set; }
    }
}
