//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_shop_cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public le_shop_cart()
        {
            this.le_cart_goodsvalue = new HashSet<le_cart_goodsvalue>();
        }
    
        public int CartID { get; set; }
        public int GoodsID { get; set; }
        public int UserID { get; set; }
        public int GoodsCount { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_cart_goodsvalue> le_cart_goodsvalue { get; set; }
        public virtual le_goods le_goods { get; set; }
        public virtual le_users le_users { get; set; }
    }
}
