//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public le_users()
        {
            this.le_shop_cart = new HashSet<le_shop_cart>();
            this.le_user_address = new HashSet<le_user_address>();
            this.le_orders_head = new HashSet<le_orders_head>();
        }
    
        public int Users_ID { get; set; }
        public string UsersName { get; set; }
        public string UsersNickname { get; set; }
        public string UsersPassWord { get; set; }
        public string Salt { get; set; }
        public string UsersEmail { get; set; }
        public string UsersImage { get; set; }
        public string UsersMobilePhone { get; set; }
        public string UsersLandline { get; set; }
        public int UsersGender { get; set; }
        public Nullable<System.DateTime> UsersLoginTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UsersStatus { get; set; }
        public string UsersAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_shop_cart> le_shop_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_user_address> le_user_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<le_orders_head> le_orders_head { get; set; }
    }
}
