//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class le_weixinmp
    {
        public string AppID { get; set; }
        public string OriginalID { get; set; }
        public string AppSecret { get; set; }
        public string QrcodeUrl { get; set; }
        public string Alias { get; set; }
        public string Nickname { get; set; }
        public string HeadImg { get; set; }
        public string PrincipalName { get; set; }
    }
}
